linux_gmp:
  stage: build
  script:
    - autoreconf -i
    - ./configure
    - make
    - make check
  artifacts:
    paths:
      - test-suite.log
  tags:
    - linux
linux_gwnum:
  stage: build
  script:
    - ./gwnum_linux.sh
  artifacts:
    paths:
      - test-suite.log
  tags:
    - linux
