/* automatically generated by rust-bindgen 0.72.1 */

pub const ECM_VERSION: &[u8; 6] = b"7.0.6\0";
pub const ECM_EC_TYPE_MONTGOMERY: u32 = 1;
pub const ECM_EC_TYPE_WEIERSTRASS: u32 = 2;
pub const ECM_EC_TYPE_HESSIAN: u32 = 3;
pub const ECM_EC_TYPE_TWISTED_HESSIAN: u32 = 4;
pub const ECM_EC_TYPE_WEIERSTRASS_COMPLETE: u32 = 5;
pub const ECM_LAW_AFFINE: u32 = 1;
pub const ECM_LAW_HOMOGENEOUS: u32 = 2;
pub const ECM_MOD_NOBASE2: i32 = -1;
pub const ECM_MOD_DEFAULT: u32 = 0;
pub const ECM_MOD_MPZ: u32 = 1;
pub const ECM_MOD_BASE2: u32 = 2;
pub const ECM_MOD_MODMULN: u32 = 3;
pub const ECM_MOD_REDC: u32 = 4;
pub const ECM_ECM: u32 = 0;
pub const ECM_PM1: u32 = 1;
pub const ECM_PP1: u32 = 2;
pub const ECM_USER_ERROR: i32 = -2;
pub const ECM_ERROR: i32 = -1;
pub const ECM_NO_FACTOR_FOUND: u32 = 0;
pub const ECM_FACTOR_FOUND_STEP1: u32 = 1;
pub const ECM_FACTOR_FOUND_STEP2: u32 = 2;
pub const ECM_DEFAULT_B1_DONE: f64 = 1.0;
pub const ECM_PARAM_DEFAULT: i32 = -1;
pub const ECM_PARAM_SUYAMA: u32 = 0;
pub const ECM_PARAM_BATCH_SQUARE: u32 = 1;
pub const ECM_PARAM_BATCH_2: u32 = 2;
pub const ECM_PARAM_BATCH_32BITS_D: u32 = 3;
pub const ECM_PARAM_WEIERSTRASS: u32 = 5;
pub const ECM_PARAM_HESSIAN: u32 = 6;
pub const ECM_PARAM_TWISTED_HESSIAN: u32 = 7;
pub const ECM_PARAM_TORSION: u32 = 8;
pub const ECM_DEFAULT_B2: i32 = -1;
pub const ECM_DEFAULT_K: u32 = 0;
pub const ECM_DEFAULT_S: u32 = 0;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type FILE = _IO_FILE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_marker {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_codecvt {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_wide_data {
    _unused: [u8; 0],
}
pub type _IO_lock_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _IO_FILE {
    pub _flags: ::std::os::raw::c_int,
    pub _IO_read_ptr: *mut ::std::os::raw::c_char,
    pub _IO_read_end: *mut ::std::os::raw::c_char,
    pub _IO_read_base: *mut ::std::os::raw::c_char,
    pub _IO_write_base: *mut ::std::os::raw::c_char,
    pub _IO_write_ptr: *mut ::std::os::raw::c_char,
    pub _IO_write_end: *mut ::std::os::raw::c_char,
    pub _IO_buf_base: *mut ::std::os::raw::c_char,
    pub _IO_buf_end: *mut ::std::os::raw::c_char,
    pub _IO_save_base: *mut ::std::os::raw::c_char,
    pub _IO_backup_base: *mut ::std::os::raw::c_char,
    pub _IO_save_end: *mut ::std::os::raw::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::std::os::raw::c_int,
    pub _flags2: ::std::os::raw::c_int,
    pub _old_offset: __off_t,
    pub _cur_column: ::std::os::raw::c_ushort,
    pub _vtable_offset: ::std::os::raw::c_schar,
    pub _shortbuf: [::std::os::raw::c_char; 1usize],
    pub _lock: *mut _IO_lock_t,
    pub _offset: __off64_t,
    pub _codecvt: *mut _IO_codecvt,
    pub _wide_data: *mut _IO_wide_data,
    pub _freeres_list: *mut _IO_FILE,
    pub _freeres_buf: *mut ::std::os::raw::c_void,
    pub __pad5: usize,
    pub _mode: ::std::os::raw::c_int,
    pub _unused2: [::std::os::raw::c_char; 20usize],
}
pub type mp_limb_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __mpz_struct {
    pub _mp_alloc: ::std::os::raw::c_int,
    pub _mp_size: ::std::os::raw::c_int,
    pub _mp_d: *mut mp_limb_t,
}
pub type mpz_t = [__mpz_struct; 1usize];
pub const gmp_randalg_t_GMP_RAND_ALG_DEFAULT: gmp_randalg_t = 0;
pub const gmp_randalg_t_GMP_RAND_ALG_LC: gmp_randalg_t = 0;
pub type gmp_randalg_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct __gmp_randstate_struct {
    pub _mp_seed: mpz_t,
    pub _mp_alg: gmp_randalg_t,
    pub _mp_algdata: __gmp_randstate_struct__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union __gmp_randstate_struct__bindgen_ty_1 {
    pub _mp_lc: *mut ::std::os::raw::c_void,
}
pub type gmp_randstate_t = [__gmp_randstate_struct; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __ell_curve_struct {
    pub type_: ::std::os::raw::c_int,
    pub law: ::std::os::raw::c_int,
    pub a4: mpz_t,
    pub a1: mpz_t,
    pub a3: mpz_t,
    pub a2: mpz_t,
    pub a6: mpz_t,
    pub buf: [mpz_t; 10usize],
    pub disc: ::std::os::raw::c_int,
    pub sq: [mpz_t; 10usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct __ecm_param_struct {
    pub method: ::std::os::raw::c_int,
    pub x: mpz_t,
    pub y: mpz_t,
    pub param: ::std::os::raw::c_int,
    pub sigma: mpz_t,
    pub sigma_is_A: ::std::os::raw::c_int,
    pub E: *mut __ell_curve_struct,
    pub go: mpz_t,
    pub B1done: f64,
    pub B2min: mpz_t,
    pub B2: mpz_t,
    pub k: ::std::os::raw::c_ulong,
    pub S: ::std::os::raw::c_int,
    pub repr: ::std::os::raw::c_int,
    pub nobase2step2: ::std::os::raw::c_int,
    pub verbose: ::std::os::raw::c_int,
    pub os: *mut FILE,
    pub es: *mut FILE,
    pub chkfilename: *mut ::std::os::raw::c_char,
    pub TreeFilename: *mut ::std::os::raw::c_char,
    pub maxmem: f64,
    pub stage1time: f64,
    pub rng: gmp_randstate_t,
    pub use_ntt: ::std::os::raw::c_int,
    pub stop_asap: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub batch_s: mpz_t,
    pub batch_last_B1_used: f64,
    pub gpu: ::std::os::raw::c_int,
    pub gpu_device: ::std::os::raw::c_int,
    pub gpu_device_init: ::std::os::raw::c_int,
    pub gpu_number_of_curves: ::std::os::raw::c_uint,
    pub gw_k: f64,
    pub gw_b: ::std::os::raw::c_ulong,
    pub gw_n: ::std::os::raw::c_ulong,
    pub gw_c: ::std::os::raw::c_long,
    pub gw_cl_flag: ::std::os::raw::c_long,
}
pub type ecm_params = [__ecm_param_struct; 1usize];
unsafe extern "C" {
    pub fn ecm_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn ecm_factor(
        arg1: *mut __mpz_struct,
        arg2: *mut __mpz_struct,
        arg3: f64,
        arg4: *mut __ecm_param_struct,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn ecm_init(arg1: *mut __ecm_param_struct);
}
unsafe extern "C" {
    pub fn ecm_reset(arg1: *mut __ecm_param_struct);
}
unsafe extern "C" {
    pub fn ecm_clear(arg1: *mut __ecm_param_struct);
}
